In [19]:
import pandas as pd
import numpy as np
sname = pd.read_csv('E:\JUET\Projects\MsEngage\'22\Model\MoodyLyrics\MoodyLyrics\ml_raw.csv')
lyrics = pd.read_csv('E:\JUET\Projects\MsEngage\'22\Model\MoodyLyrics\MoodyLyrics\lyrics-data.csv')

In [61]:
x,y = sname['Artist'],lyrics['SName'][123295:125890]
# lyrics['SName'][123295:125890]
# y = y.reset_index()
# sname['Common'] = np.where(x == y, 'True', 'False')

In [51]:
len(lyrics['SName'].unique())

267259

In [50]:
len(sname['Artist'].unique())

1672

In [64]:
lt = []
for i in sname['Title']:
    flag = 0
    for j in lyrics['SName'][123295:143240]:
        if i == j:
            lt.append(True)
            flag = 1
            break
    if flag == 0:
        lt.append(False)

In [55]:
len(lt)

2595

In [66]:
ltl = []
for i in lyrics['SName']:
    flag = 0
    for j in sname['Title']:
        if i == j:
            ltl.append(True)
            flag = 1
            break
    if flag == 0:
        ltl.append(False)

In [65]:
sname[lt]

       Index              Artist          Title     Mood
18      ML19       Jordin Sparks    Battlefield    angry
21      ML22              Tyrese            One  relaxed
26      ML27  The Rolling Stones  Gimme Shelter    angry
27      ML28  The Rolling Stones          Happy    happy
34      ML35             Glasser           Home  relaxed
...      ...                 ...            ...      ...
2547  ML2548   Killswitch Engage       Unbroken    angry
2558  ML2559         Joe Jackson        Lullaby      sad
2565  ML2566            Bee Gees    Night Fever      sad
2582  ML2583           Metallica  Metal Militia      sad
2586  ML2587         Boyz II Men   Silent Night  relaxed

[434 rows x 4 columns]

In [67]:
lyrics[ltl]

,ALink,SName,SLink,Lyric,language
190,/ivete-sangalo/,My Love,/ivete-sangalo/my-love.html,"My love, eu amo você\nÉ tanto amor que em mim ...",pt
708,/banda-eva/,My Love,/banda-eva/my-love.html,"My love, eu amo você\nÉ tanto amor que em mim ...",pt
863,/e-o-tchan/,I Love You,/e-o-tchan/i-love-you.html,"Ô, ô, ô, ô...\n\nTá gostoso\nTá gostoso\nTá go...",pt
1508,/daniela-mercury/,And I Love Her,/daniela-mercury/and-i-love-her.html,I give her all my love\nthats all I do\nand If...,en
2213,/asa-de-aguia/,Take It Easy,/asa-de-aguia/take-it-easy.html,Intro: G C\n\nG\nSentindo a noite vazia\nF C\n...,pt
...,...,...,...,...,...
377657,/angela-maria/,Amor,/angela-maria/amor.html,\nA7+ E7 A7+\nAmor amor amor\nNasceu de mim\nB...,pt
379767,/ofra-haza/,Innocent,/ofra-haza/innocent.html,Hashamaim ... sadot\nun'dudei adam lemilchamot...,no
379776,/ofra-haza/,Love Song,/ofra-haza/love-song.html,SIMENI KAHOTAM AL LIBECHA'\nSIMENI KAHOTAM AL ...,NaN
379788,/ofra-haza/,You,/ofra-haza/you.html,OOh\n\nLate in life\nYou came to me\nAnd you p...,en
379925,/clegg-johnny/,The Promise,/clegg-johnny/the-promise.html,Electric chair didn't burn a hair\nand the new...,en